### PR TITLE
LPS-100653 Delete experiment in AC when deleting in DXP

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77932. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/8a3dfd593e30~1...8a3dfd593e30) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
