### PR TITLE
LRDOCS-893 Add Javadoc for most methods of AssetTagLocalServiceImpl

### PR DESCRIPTION
**Pull request by adolfopa**
To generate stubs for the remaining methods, see below:

    Ways to generate Javadoc

        Three Options: ant format-javadoc
            -Dlimit=ClassName or “ClassName1,ClassName2,com.liferay.portal.*”
            -Dupdate=true : Inserts place holders for comment elements that are not up to date with the current method signatures.

            -Dinit=true : Inserts place holders for all comment elements.

### CODE REVIEW

**Comment by epgarcia** [comment]
Hi @jrao,

I've reviewed the javadocs and in general they're fine. Just one comment: I've noticed that the way in which the group/groupId parameter is described is not consistent. For example, in addTag we describe it as the "site in which the asset tag is to be added" while in others it's the primary key of the site or the primary key of the group. I think we should always use the same term (group or site) and also make clear whether the parameter is the key or the object itself (e.g in checkTags it's clear that in one method we pass the primaryKey and in other the group as object).

Could you please review this? As I said, apart from this everything looks ok.

Thanks!

**Comment by jrao** [comment]
@epgarcia Thanks, Eduardo! Will review and resend.

@juliocamarero

**Comment by jrao** [comment]
@epgarcia Sent https://github.com/epgarcia/liferay-portal/pull/310

@juliocamarero

**Pull request closed without merging**
