### PR TITLE
LPS-91058 Regen

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68886. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/f5175d50c690~3...f5175d50c690) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/27. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/f5175d50c690~3...f5175d50c690) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
