### PR TITLE
LPS-141925 Include Icons in theme so that it Dialect can work for Commerce.

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:forward

**Comment by ethib137** [comment]
ci:reevaluate:1297401_688

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:reevaluate:1287401_925

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:forward

**Pull request closed without merging**
