### PR TITLE
LPS-94941 Build lang

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/57. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/0dbc6509ce34~1...0dbc6509ce34) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
