### PR TITLE
Bugs front

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by andresfulla** [comment]
ci:test:sf

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Bugs LPS-102635 and LPS-102557

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79187. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/476e82998de1~1...476e82998de1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
