### PR TITLE
Changes in video fragments thumbnails

### PR DESCRIPTION
**Pull request by atjuan**

### CODE REVIEW

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:reevaluate:1287401_24

**Comment by epgarcia** [comment]
ci:reevaluate:1287401_24

**Comment by epgarcia** [comment]
ci:forward

**Pull request closed without merging**
