### PR TITLE
Experiments front

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by andresfulla** [comment]
ci:test:sf

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75584. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/ddb28a450623~2...ddb28a450623) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
