### PR TITLE
LPS-91334 Render keywords metatag with the tags on Journal Display

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @pedroqueiroz

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68824. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/daafd3a67e71~1...daafd3a67e71) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
