### PR TITLE
LPS-94426 Build Lang

### PR DESCRIPTION
**Pull request by darquesdev**
Re-enable PortletTitleTest when this is merged

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71968. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
