### PR TITLE
LPS-85968 - As a segments administrator, I can create dynamic user segments based on complex queries

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64053. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64062. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/9ad75daeeb26~1...9ad75daeeb26) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
