### PR TITLE
LPS-98453

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76473. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/4bb5349398d0~3...4bb5349398d0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
