### PR TITLE
LPS-91943

### PR DESCRIPTION
**Pull request by dgarciasarai**
@epgarcia @andresfulla

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Missing a couple of tests for this pull request. Waiting for the CI.

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73127. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
