### PR TITLE
LPS-99886

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77834. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77842. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/d2675322a348~1...d2675322a348) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77852. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/57fc57e4bc06~1...57fc57e4bc06) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
