### PR TITLE
LPS-87431 Initial AsahClient implementation

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65640. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/0b5d37df425a~7...0b5d37df425a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
