### PR TITLE
Experiment with winner and no winner declared

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78081. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/c305f8487604~2...c305f8487604) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
