### PR TITLE
LPS-142117 Masterclass sign in broken pages

### PR DESCRIPTION
**Pull request by atjuan**
- LPS-142122 Fix logo link in sign in fragment
- LPS-142117 correct the styles of the login portlet inputs

### CODE REVIEW

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
See #1150

**Pull request closed without merging**
