### PR TITLE
LPS-142641 Department Initializer WIP

### PR DESCRIPTION
**Pull request by atjuan**
- LPS-142641 Add content and categories to journal articles
- LPS-142641 Add first master page
- LPS-142641 Fragment polishing
- LPS-142641 Stylebook update

### CODE REVIEW

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
See #1164

**Pull request closed without merging**
