### PR TITLE
LPS-137941 - Add styles for form text inputs to Dialect theme

### PR DESCRIPTION
**Pull request by ethib137**
CC: @marcoscv-work

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Looks great!! go ahead with it!

just a suggestion, since we are removing the CSS variable reference (since we remove the SASS variable) and we trust in the fact the stylebook will provide the variable, it can be a little risky if they are not totally synchronized or loaded at the same time, someone remove a token, etc.. for those cases, I would recommend adding CSS custom properties fallbacks like:

`color: var(--variable, red);`

**Comment by epgarcia** [comment]
ci:forward

**Pull request closed without merging**
