### PR TITLE
Lps 104813 master

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @achaparro

When a user is deleted that created a user segment prior to upgrading to 7.2+ the upgrade fails for UpgradeContentTargeting. We need to get a valid userId before adding it to the service context.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81245. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
