### PR TITLE
LPS-100889 Renames app entry point

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Juro que en mi local compila 😂

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/andresfulla/liferay-portal/pull/146. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/4e6d568846c6~2...4e6d568846c6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
