### PR TITLE
LPS-100500

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Pull request submitted here https://github.com/brianchandotcom/liferay-portal/pull/78178

**Pull request closed without merging**
