### PR TITLE
LPS-144166 Improve Page Responsiveness

### PR DESCRIPTION
**Pull request by atjuan**
- LPS-144166 Fix responsive text alignment issues in DPTs
- LPS-144166 Fix responsive text alignment issues in home page
- LPS-144166 SF

### CODE REVIEW

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:forward

**Pull request closed without merging**
