### PR TITLE
LPS-96682 BuildService

### PR DESCRIPTION
**Pull request by darquesdev**
@ealonso

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/816. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/7e9c0f1abb92~1...7e9c0f1abb92) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74774. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/7e9c0f1abb92~1...7e9c0f1abb92) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
