### PR TITLE
LPS-105093 Hide display views options since only table will be used

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81654. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/e175934c0621~1...e175934c0621) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
