### PR TITLE
LPS-91512 Get users from segment

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
@epgarcia I regenerate again, one thing was missing.

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69096. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/0da202ca1b6c~1...0da202ca1b6c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69100. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/63fcdfc199cd~1...63fcdfc199cd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
