### PR TITLE
LPS-139514 - Add Styles for checkboxes and radios.

### PR DESCRIPTION
**Pull request by ethib137**
cc: @marcoscv-work

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1337401_111

**Comment by ethib137** [comment]
ci:reevaluate:1337401_111

**Comment by epgarcia** [comment]
ci:reevaluate:1337401_111

**Comment by marcoscv-work** [comment]
Looks great!

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1267401_279

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:forward

**Pull request closed without merging**
