### PR TITLE
LPS-92803 Fix bug with pagination in content sets API

### PR DESCRIPTION
**Pull request by dgarciasarai**
/cc @rubenpulido @ealonso @nhpatt

See https://github.com/dgarciasarai/liferay-portal/pull/46 (sf success and relevant running)
See https://github.com/brianchandotcom/liferay-portal/pull/70758#issuecomment-479725937

### CODE REVIEW

**Comment by dgarciasarai** [comment]
We have to discuss this :)

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70829. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Thanks!

**Pull request closed without merging**
