### PR TITLE
LPS-100305 [BUG] Change key to MAX_SCROLL_DEPTH

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77526. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/594b88940094~2...594b88940094) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77527. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/1557042f30bc~2...1557042f30bc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
