### PR TITLE
LPS-107151 As a site admin, I want to assign site roles to site-level segments

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-107151](https://issues.liferay.com/browse/LPS-107151).<br><br>Hey @epgarcia, this adds the site role assignment for segments entries. Please let me know what you think. Thanks!<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @rotty3000

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@pyoo47 is this one I can retest?

**Comment by pyoo47** [comment]
@drewbrokke Yes based on the number of slave nodes, the previous test used, it should be small enough but I guess the question is, "Did something change that makes me think that it will pass the next time?"

**Comment by drewbrokke** [comment]
@patriciajeanperez would you be willing to verify the functional test failures above? Specifically CPRoles#AssignExistingSegmentToRegularRole and LocalFile.CPRoles#RemoveSegmentFromRegularRole. I'll take a look as well.

**Comment by drewbrokke** [comment]
@patriciajeanperez please see https://github.com/epgarcia/liferay-portal/pull/1009/commits/6221538310577d18888b110cc5982c3f3bdaefa1

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
There're 3 failed POSHI tests, one is more like flaky, and another two will be quarantined in [LRQA-57107](https://github.com/brianchandotcom/liferay-portal/commit/4f44e1d3761f138432bf6348f1783cb8bfc22629) and [LRQA-57061](https://github.com/brianchandotcom/liferay-portal/pull/86811/commits/7bb166cc1b9d2cb3eb4bc0cef928741120aeccfd), we can re-trigger the ci after the commits get merged.

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez somehow I forgot to push my local version bump commit. I just force-pushed it and am retesting.

**Comment by drewbrokke** [comment]
@patriciajeanperez any idea why it says that the semver failure is in common with upstream? It should only affect this branch.

**Comment by patriciajeanperez** [comment]
Hey @drewbrokke, looks like the results were being compared with acceptance at https://github.com/epgarcia/liferay-portal/commit/1d0f67c4f582177577e292e34c19451619843d5b which was from January. It should appear under unique failures once Eduardo pulls/pushes.

**Comment by Sharryxue** [comment]
ci:test:relevant
The only failed functional test is more like flaky and quarantined in LRQA-57264.

**Comment by drewbrokke** [comment]
PR sent to https://github.com/ealonso/liferay-portal/pull/2878

**Pull request closed without merging**
