### PR TITLE
LPS-51136 - adding polls portlet to community site tamplate

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Hi @linolaoj, 

Under which circumstances would we get a NoSuchResourceActionException exception in the addPublicSite method? 

Thanks!

**Comment by linolaoj** [comment]
Hi @epgarcia , 

I noticed that when the portal is started for the first time and goes to configuration page NoSuchResourceActionException is raised. I am not sure how to avoid it so I put the try catch.

Thanks!

**Comment by epgarcia** [comment]
See brianchandotcom/liferay-portal/pull/32392.

Thanks!

**Pull request closed without merging**
