### PR TITLE
Lps 88763

### PR DESCRIPTION
**Pull request by Preston-Crary**
See https://github.com/brianchandotcom/liferay-portal/pull/66351#issuecomment-45289525

It's less code, easier to understand and faster to just create the instance ourselves.  I think this is only useful if the implementation is internal and usage are in separate bundles or if you expect someone to implement another one at a higher service ranking.  Since the interface is internal that's not possible so calling new ourselves is best.

Hope that explains my reasoning on this change.

### CODE REVIEW

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66626. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
