### PR TITLE
LPS-94470 Use updated list of segments to retrieve the associated experiences

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72076. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/6317a46fa55b~1...6317a46fa55b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72077. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/74adb48e038c~1...74adb48e038c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
