### PR TITLE
LPS-142641 Team Extranet Initializer

### PR DESCRIPTION
**Pull request by atjuan**
- LPS-142641 Job position dpt
- LPS-142641 Master pages fixes
- LPS-142641 Blog entry dpt fixes
- LPS-142641 Social links fragment
- LPS-142641 Fragment fixes
- LPS-142641 Position entry text fix
- LPS-142641 SF
- LPS-142641 Home page fixes
- LPS-142641 Job position dpt fixes
- LPS-142641 Position card fragment fixes
- LPS-142641 Team member dpt
- LPS-142641 Display page templates layout fixes
- LPS-142641 New site logo
- LPS-142641 Naviation menus new format
- LPS-142641 Team Extranet rename

### CODE REVIEW

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:relevany

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
#1169

**Pull request closed without merging**
