### PR TITLE
LPS-57392 As a page administrator I want to create a page without content so that it can act just as a container for their children pages

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
Fixed source formatting

**Comment by cgoncas** [comment]
ci:retest

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
ci:retest

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
See brianchandotcom/liferay-portal/pull/29032.

Thanks

**Pull request closed without merging**
