### PR TITLE
LPS-138325 - Add Styles for form select inputs.

### PR DESCRIPTION
**Pull request by ethib137**
cc: @marcoscv-work

This one adds supports for select inputs but is mostly making use of additional clay sass and also applying some of the ideas I've discussed with @pat270 at the same time.

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM!!!!

**Comment by epgarcia** [comment]
ci:forward

**Pull request closed without merging**
