### PR TITLE
LPS-102889 No historical data is available to estimate the duration of the test

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Fixes bug LPS-102828 and the related story LPS-102889.

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Review https://github.com/epgarcia/liferay-portal/pull/982/commits/ff3b998ec71fba98c3bf47f86415ce3f91aca25d with @darquesdev

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80313. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/16aef7130e87~1...16aef7130e87) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80315. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/e7eea8750964~1...e7eea8750964) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
