### PR TITLE
LPS-55151 XSL content portlet doesn't accept XML and XSL file with internal URL

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Sent to Brian brianchandotcom/liferay-portal/pull/26043.

Thanks!

**Pull request closed without merging**
