### PR TITLE
LPS-96828 Mark portlets as used / not used when removing the experience

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
@victorg1991 this might be interesting for you. Thanks!

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/393. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/960e9e80407d~2...960e9e80407d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/394. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/24e879c506c1~2...24e879c506c1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
