### PR TITLE
LPS-91794 Regen

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69597. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/6a35e585e60d~3...6a35e585e60d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69598. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/0a631e35638a~3...0a631e35638a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
