### PR TITLE
[TECHNICAL-SUPPORT] LPS-68191

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler @ericyanLr

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by ericyanLr** [comment]
Hey @epgarcia @jonathanmccann,

After further testing,  I found that if we do not include the last SF commit: https://github.com/epgarcia/liferay-portal/pull/564/commits/27ef2f0762023ac99e267d27bd4f3d27a553159a, the tests pass.
But, looking at the SF, I'm not sure what part is making it not pass the tests.

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Hi @BryanEngler 

I run tests locally and as @ericyanLr said they seem to fail with the last SF commit (but not with the previous one). Could you take a look to it?

Thanks

**Pull request closed without merging**
