### PR TITLE
[Technical Support] LPS-61134 To field of Unit converter is not updated - redirection loop problem

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Eduardo,

the Support QA found an other problem with language handling in URLs that has not been caused by our modifications but John handled this also as he is familiar with the working of this.

I am sending this to you as I sent all the others like this before.

This change the logic a bit as with this change there is no more redirection from the language id to the default language code anymore, like as it was in the case, for example, at using /en_US that was redirected to simple /en before.

Using /en_US in the URL stays on /en_US, however, I cannot see other way to solve the redirection loop. Anyway, I do not know if that made any sense o redirect to the default language code at all before this modification. You may know this better.

For testing, it is not necessary to use WSRP portlet as it is in the ticket description as original step by steps. It is enough to use the simple reproduction steps.

Please, let us know if you have any concerns or any other idea to address this problem.

Thank you in advance,
Zsigmond

### CODE REVIEW

**Comment by zxdgoal** [comment]
we also have post a thread on WEM forum.

**Comment by zsigmondrab** [comment]
Hi Eduardo,

I cannot see that the current fix would have made the tests fail. Let me know if I am wrong.

Regards,
Zsigmond

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34177. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Hi @zsigmondrab,

It was the changes in the test that made the other tests to break. You have to restore the PropsValues.LOCALES_ENABLED property to its original value.

Thanks!

**Comment by zsigmondrab** [comment]
Thank you very much for taking care of the test.

We will watch cases like this in the future.

Zsigmond

**Pull request closed without merging**
