### PR TITLE
LPS-56789 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
hey @epgarcia, this is random css failure. I think it's safe now :)

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Please see marcellustavares/liferay-portal/pull/608.

Thanks!

**Pull request closed without merging**
