### PR TITLE
LPS-100890 Renames app entry point

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
https://github.com/jbalsas/liferay-portal/pull/1972

**Comment by dgarciasarai** [comment]
ci:close

**Pull request closed without merging**
