### PR TITLE
LPS-100906 Copy portlet preferences when creating experiences/variants to personalized widgets

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78254. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
