### PR TITLE
LPS-101184 Publish any variant and hiding pause/restart buttons

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78130. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/6776bcc29b71~1...6776bcc29b71) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
