### PR TITLE
LPS-58569

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
@epgarcia 
At pull https://github.com/jorgediaz-lr/liferay-portal/pull/15 I have tested the new unit test without the code that fixes the problem. You can see it fails: JournalTestUtilTest.testDeleteDDMStructureWithDefaultValues

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
See brianchandotcom/liferay-portal/pull/30390.

Thanks!

**Pull request closed without merging**
