### PR TITLE
LPS-134591 - Add fully customizable button styles to solutions theme.

### PR DESCRIPTION
**Pull request by ethib137**
cc: @marcoscv-work

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test

**Comment by ethib137** [comment]
ci:test

**Comment by ethib137** [comment]
ci:reevaluate:1107401_4916

**Comment by ethib137** [comment]
ci:reevaluate:1107401_4916

**Comment by ethib137** [comment]
ci:reevaluate:1107401_4916

**Comment by marcoscv-work** [comment]
LGTM ! ;-) !

**Comment by epgarcia** [comment]
@ethib137 I'll make sure the test go green as part of my review, no worries :)

**Pull request closed without merging**
