### PR TITLE
LPS-61592 fix basic information tab name

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
Seems to be random test failure, different fail each time.

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34161. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
