### PR TITLE
LPS-99230, LPS-99234 and LPS-99235

### PR DESCRIPTION
**Pull request by dgarciasarai**
/cc @andresfulla

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76566. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
