### PR TITLE
LPS-102337 AB Testing URL Improvements

### PR DESCRIPTION
**Pull request by darquesdev**
from https://github.com/epgarcia/liferay-portal/pull/976

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79296. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
