### PR TITLE
LPS-99829 Add a button to change the status from Running to Stopped

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77521. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/98ec67569d6b~1...98ec67569d6b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
