### PR TITLE
LPS-100500

### PR DESCRIPTION
**Pull request by dgarciasarai**
On top of https://github.com/epgarcia/liferay-portal/tree/pr-943
* Validation split 0-1
* Check editable in run experiment service
* Add Integration test

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/948. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/3ef19afe8173~5...3ef19afe8173) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77880. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/9858bacdd1ab~5...9858bacdd1ab) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
