### PR TITLE
LPS-102337 AB Testing URL params improvements

### PR DESCRIPTION
**Pull request by darquesdev**
@manoelcyreno 

Related bugs:
- https://issues.liferay.com/browse/LPS-102337
- https://issues.liferay.com/browse/LPS-100224
- https://issues.liferay.com/browse/LPS-100842
- https://issues.liferay.com/browse/LPS-100222
- https://issues.liferay.com/browse/LPS-102565
- https://issues.liferay.com/browse/LPS-102819

Use cases: 
- [AB Testing Sidebar vs Rendered Page](https://docs.google.com/document/d/1cBEhxJJjDOPJPlr8UFjVSOuBRPLsU8q2nKfPpleSLm0)

CC: @andresfulla

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
review https://github.com/epgarcia/liferay-portal/pull/979

**Pull request closed without merging**
