### PR TITLE
LPS-94731 Add tests for segments users headless API

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79230. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/e9b930ddade4~1...e9b930ddade4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/978. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/2f745889a604~1...2f745889a604) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79247. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/2f745889a604~1...2f745889a604) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
