### PR TITLE
LPS-95667 Build lang

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74194. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/5a300cf0e63d~1...5a300cf0e63d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
