### PR TITLE
Revert "LPS-42524 NoSuchLayoutException when a page created from site template no longer exists in site template"

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/liferay/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged please re-run this particular pull request.

Sorry for the inconvenience.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
See brianchandotcom/liferay-portal/pull/34483.

Thanks!

**Pull request closed without merging**
