### PR TITLE
LPS-142641 Site Initializer Department WIP 02

### PR DESCRIPTION
**Pull request by atjuan**
- LPS-142641 Module creation
- LPS-142641 Rename other resources
- LPS-142641 Create wc structures and templates
- LPS-142641 Rename images
- LPS-142641 Remove masters and templates
- LPS-142641 Create pages and navigation menus
- LPS-142641 Create categories, collections and roles
- LPS-142641 Clean fragments
- LPS-142641 Create department stylebook
- LPS-142641 Add provisional site thumbnail and logo

### CODE REVIEW

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
See #1159

**Pull request closed without merging**
