### PR TITLE
LPS-87867 Support boolean types in custom field queries

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@darquesdev This failure is actually a compile issue:

```
     [exec] > Task :private:apps:oauth:oauth-service:compileJava FAILED
     [exec] 
     [exec] > Task :private:apps:portal-cache:portal-cache-multiple:deploy
     [exec] Files of project ':private:apps:portal-cache:portal-cache-multiple' deployed to /opt/dev/projects/github/liferay-portal/bundles/osgi/portal
     [exec] 
     [exec] > Task :private:apps:portal-cache:portal-cache-multiple:deployDependencies NO-SOURCE
     [exec] /opt/dev/projects/github/liferay-portal/modules/private/apps/oauth/oauth-service/src/main/java/com/liferay/oauth/model/impl/OAuthApplicationCacheModel.java:64: error: cannot find symbol
     [exec] 		return HashUtil.hash(0, oAuthApplicationId);
     [exec] 		       ^
     [exec]   symbol:   variable HashUtil
     [exec]   location: class OAuthApplicationCacheModel
     [exec] /opt/dev/projects/github/liferay-portal/modules/private/apps/oauth/oauth-service/src/main/java/com/liferay/oauth/model/impl/OAuthUserCacheModel.java:64: error: cannot find symbol
     [exec] 		return HashUtil.hash(0, oAuthUserId);
     [exec] 		       ^
     [exec]   symbol:   variable HashUtil
     [exec]   location: class OAuthUserCacheModel
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/private/apps/oauth/oauth-service/src/main/java/com/liferay/oauth/service/upgrade/OAuthServiceUpgrade.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 4 errors
```

**Comment by darquesdev** [comment]
Thx @pyoo47 I'll try it later

**Comment by darquesdev** [comment]
ci:test:relevant

**Pull request closed without merging**
