### PR TITLE
LPS-143145 - Add styles and style book configurations for Card Components

### PR DESCRIPTION
**Pull request by ethib137**
cc: @marcoscv-work

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
**Looks good to me!**

I was changing the theme and I saw that the style:
```
.token-border {
	border: 1px solid var(--color-neutral-5);
}
```
Makes looks like broken the borders in classic theme when we use the `dialect-style-guide-sample-web`. I know the focus of the module is to test Dialect theme but I think we could avoid it looks broken with ther themes just by removing the class or change the color variable to a basic one.

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by ethib137** [comment]
Thanks @marcoscv-work... I like your suggestion. I created a ticket for it here: https://issues.liferay.com/browse/LPS-143512

**Pull request closed without merging**
