### PR TITLE
LPS-141925 - Include Icons in theme so that it Dialect can work for Commerce.

### PR DESCRIPTION
**Pull request by ethib137**
Good morning @epgarcia and @marcoscv-work, 

I've got a bunch of little tickets contained in here. One ticket to draw your attention to is LPS-141038. In this ticket I remove tokens from Classic that are not needed in Dialect. I then remove the dialect prefix from the token categories and reorganize the tokens appropriately. 

Initially, I tried to keep Dialect tokens carefully isolated from Classic tokens because we had the plan to have the Dialect theme be temporary until we could create a Design pack that could contain all necessary changes. Keeping the tokens separate will facilitate this eventual move. This is no longer the plan, at least not at any time in the near future which is due to the following reasons:
- In order to restyle Clay, best practices dictated overriding Clay sass variables. Currently this is only possible in a theme.
- Design Packs are still not ready and there is no guaranteed date at which they will be ready with the features we require.
- From discussions with PMs, I have understood that Classic will not be the only theme. They have an expectation that we will likely have additional themes for different purposes, Dialect likely being one of them.

Please let me know if you have any more questions. I'm really hoping you guys will have time to send this on before the end of the week.

Thanks.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1297401_665

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM!

**Comment by epgarcia** [comment]
See #1140

**Pull request closed without merging**
