### PR TITLE
LPS-99718 No description for Check Interval in Systems Settings > Segments

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76974. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/877ce7f8f046~2...877ce7f8f046) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
