### PR TITLE
LPS-99331 and LPS-99332 Create and edit experiment goal

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
See https://github.com/epgarcia/liferay-portal/pull/904

**Pull request closed without merging**
