### PR TITLE
LPS-101906 Cannot update or delete experience if has a locked segments experiment

### PR DESCRIPTION
**Pull request by dgarciasarai**
- [x] Add exceptions if the SegmentsExperience has a locked SegmentsExperiment
- [x] Add tests

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80312. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/e58975a17e08~1...e58975a17e08) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
