### PR TITLE
LPS-90987 Get user segments

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
@dgarciasarai please apply changes in 1d2a773eb7d5998e1f92670ab0c7b881d15a4d6d. Thanks!

**Comment by dgarciasarai** [comment]
Sure! Thanks! :)

**Pull request closed without merging**
