### PR TITLE
LPS-91996

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69841

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69928. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/c4c4a9da2aae~2...c4c4a9da2aae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
