### PR TITLE
LPS-102798 Render a portlet using actual portlet id to take possible segment experience id into account for non-instanceable portlets

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hola Edu, tarde o temprano esto debería de aparecer :)
Echa un ojo por favor, también tiene sentido que @manoelcyreno eche un vistazo y que pasen los tests existentes(seguramente necesitamos mas tests para esta cosa tan frágil).
Gracias!

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Hi @pavel-savinov,

One question regarding the changes. In render_portlet.jsp, we're assigning `actualPortletId = PortletIdCodec.encode(portletId, instanceId);` instead of replacing the `portletId` with that value. But later, we're using the `actualPortletId` instead of `portletId` to retrieve every portlet related data, except for `checkingStagingGroup.isStagedPortlet(portletId)`. 

Should we use `actualPortletId` there too? Why? If not, could we simply reassign `portletId` to the  `PortletIdCodec.encode(portletId, instanceId)`?

Thanks

**Pull request closed without merging**
