### PR TITLE
LPS-92803 Obtain assets for a given user based on her segmentation using a headless API without Context

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70683. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
