### PR TITLE
LPS-68983 add user id to the portlet id in case when non instantiable portlet added to customizable page

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request forwarded to https://github.com/ealonso/liferay-portal/pull/776. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
