### PR TITLE
LPS-52927 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Won't merge. See my comments to LPS-52927. Thanks

**Comment by yuhai** [comment]
Hi Eduardo,

I have sent one email to you to explain the fix.

Thanks,
Hai

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
See brianchandotcom/liferay-portal/pull/23810

**Pull request closed without merging**
