### PR TITLE
LPS-68301

### PR DESCRIPTION
**Pull request by eperezg**

### CODE REVIEW

**Comment by eperezg** [comment]
ci:reopen

**Comment by epgarcia** [comment]
ci:reopen

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45627. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/c343553d~2...c343553d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
