### PR TITLE
LPS-102418 Change variants default min and max

### PR DESCRIPTION
**Pull request by dgarciasarai**
Range [1, 99]

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79026. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
