### PR TITLE
LPS-104573 Validate click goal target and variants length in service

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80951. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/46fd0b9e43cd~2...46fd0b9e43cd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80953. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/cbd6c4fdcbb3~2...cbd6c4fdcbb3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
