### PR TITLE
LPS-96094 Display content recommendation option in content set configuration

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/846. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75472. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75473. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/847. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/15557ba6da51~1...15557ba6da51) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75490. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/ab8d1d6ef11c~2...ab8d1d6ef11c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
