### PR TITLE
LPS-98282

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76071

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76080. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/5669906e8212~3...5669906e8212) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76092. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/e88ec115e462~3...e88ec115e462) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
