### PR TITLE
LPS-99286 Set experiment goal also in AC (A/B Testing)

### PR DESCRIPTION
**Pull request by dgarciasarai**
On top of https://github.com/brianchandotcom/liferay-portal/pull/76794

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76824. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/532d0db00a75~1...532d0db00a75) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76830. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/66ff8e6d4e3a~3...66ff8e6d4e3a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/908. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/d2eac9e28995~3...d2eac9e28995) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76837. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/de3cbdd7b714~3...de3cbdd7b714) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
