### PR TITLE
LPS-141036 - Apply Styles to Progress Bars and other tickets.

### PR DESCRIPTION
**Pull request by ethib137**

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
cc: @marcoscv-work

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM!

**Comment by epgarcia** [comment]
ci:forward

**Pull request closed without merging**
