### PR TITLE
LPS-68072 Automatically convert WYSIWYG portlet instances to Web Content Display instances

### PR DESCRIPTION
**Pull request by juliocamarero**
@jorgeferrer FYI

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Thanks Julio and Edu!

**Comment by peterfellwock** [comment]
ci:retest

**Comment by epgarcia** [comment]
Hi @peterfellwock 

I noticed that you're creating a copy of the BASIC WEB CONTENT structure and templates to migrate the content of the WYSIWYG portlet. If according to LPS-68072 all you need is a structure with an HTML field, why don't you just reuse the existing BASIC WEB CONTENT structure and template?

If you still wanted to create a separate structure/template pair, then I think you have to make sure they are added to all the instances (and not only the default company). That could be another reason to reuse the existing default web content structure and template.

Thanks

**Comment by JorgeFerrer** [comment]
Hey Eduardo,

@juliocamarero explicitly warned me against using BASIC WEB CONTENT because
it could have been changed by an administrator and no longer have an HTML
field. Peter had done it that way and I asked him to change it based on
that feedback from Julio.

I do agree though that making a copy of it is also risky since you don't
know what it will have. It's better to create a new one from scratch.

You also make a good point with respect to creating the structure for all
companies, but I guess that applies to the whole migration process, right?

**Comment by epgarcia** [comment]
Hi @JorgeFerrer 

I agree we cannot expect the BASIC WEB CONTENT to have the HTML field by the time the WYSIWYG portlet is updated, but then as you point we shouldn't copy it either, but create it from scratch instead. Maybe we could reuse part of the logic in journal for this (see https://github.com/liferay/com-liferay-journal/blob/7.0.x/journal-service/src/main/java/com/liferay/journal/internal/upgrade/v0_0_5/UpgradeJournal.java#L95)

As for the instances, it should be part of the upgrade process (see https://github.com/liferay/com-liferay-journal/blob/7.0.x/journal-service/src/main/java/com/liferay/journal/internal/upgrade/v0_0_5/UpgradeJournal.java#L538). If we wanted this structure/template to be available in new instances (after the migration process) then we should also add an InstanceLifecycleListener (see https://github.com/liferay/com-liferay-journal/blob/master/journal-service/src/main/java/com/liferay/journal/internal/instance/lifecycle/AddDefaultJournalStructuresPortalInstanceLifecycleListener.java#L69).

If you agree on these changes, then I'd ask @peterfellwock to take journal as a reference, rewrite his changes and send me a new PR.

Thanks!

**Comment by JorgeFerrer** [comment]
Sure, you know better than me. I was just trying to update you on the
previous conversations that you were not still part of.

**Comment by epgarcia** [comment]
Thanks @JorgeFerrer !

@peterfellwock please take the previous comments into account and resend the PR. Thx!

**Comment by peterfellwock** [comment]
@JorgeFerrer @juliocamarero @epgarcia Thank you guys for the feedback, I will get on it.

**Pull request closed without merging**
