### PR TITLE
LPS-90055 Segments ancestors

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/666. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/82a14927ccb9~4...82a14927ccb9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67624. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/e6c30c289b7e~4...e6c30c289b7e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
