### PR TITLE
LPS-96235 Add a terms of interests provider on DXP

### PR DESCRIPTION
**Pull request by dgarciasarai**
Please, review naming :)

/cc @darquesdev

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/818. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/9c1a1c495788~4...9c1a1c495788) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74836. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/9c1a1c495788~4...9c1a1c495788) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74837. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/522acd0ba77d~4...522acd0ba77d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
