### PR TITLE
LPS-137654 - Create a contributed fragment collection that contains fragments that are styled by the Solutions theme.

### PR DESCRIPTION
**Pull request by ethib137**
cc: @marcoscv-work

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
ci:forward

**Pull request closed without merging**
