### PR TITLE
LPS-95666 Create client for the new ASAH endpoint of anonymous users

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74102. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/936522e258e1~2...936522e258e1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
