### PR TITLE
LPS-96045 Frontend tests for translating special characters

### PR DESCRIPTION
**Pull request by AngeloYoun**
Hey @epgarcia,<br>
Ha, I finally fixed this lol
<br>Please let me know if you have any questions,<br>Angelo Youn

### CODE REVIEW

**Comment by epgarcia** [comment]
@AngeloYoun oh, awesome. Thanks, this is a part you know well, since you worked on it with Kevin. We'll review it today.

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:format

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
@AngeloYoun I was reviewing the pull request with @andresfulla. In the ticket, I put you some comments about it. Thanks :)
Pull request resent here: https://github.com/dgarciasarai/liferay-portal/pull/134

**Comment by dgarciasarai** [comment]
ci:close

**Pull request closed without merging**
