### PR TITLE
LPS-98887 navigate from ab test to Layout Editor

### PR DESCRIPTION
**Pull request by darquesdev**
@andresfulla @jkappler

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76987. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/46fd270fe7e2~2...46fd270fe7e2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
