### PR TITLE
LPS-100307 [BUG] The AC does not update the number of the variants

### PR DESCRIPTION
**Pull request by dgarciasarai**
Delete variant does not update the number of variants in AC

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77530. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
