### PR TITLE
LPS-99955 bug fixing

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by andresfulla** [comment]
ci:test:sf

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78192. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/e2514eb2f9d2~1...e2514eb2f9d2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78193. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/d35cf5bb8241~1...d35cf5bb8241) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
