### PR TITLE
LPS-100639, LPS-100644 and LPS-100640

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77769. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77771. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/138ee356a10f~2...138ee356a10f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
