### PR TITLE
LPS-96894 It is not clear what the Enable/Disable toggle does in System Settings

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74581. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/a3bedfded74f~2...a3bedfded74f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
