### PR TITLE
LPS-55243

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/26042

Thx

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Hey @brianchandotcom,

I actually used Web Content Util only as label for the panel (variable group) that contains the list of util variables for web content templates in the template editor, in the same way as Web Content Services was being used as label for the panel that contains the list of service variables.  The variables themselves always have their code level names (e.g. journalUtil, journalArticleService...).

If you still want me to rename the panel labels, then I assume I should also change the one for services. In that case, and just to confirm, should I use journal-content-util and journal-content-services? or simply journal-util and journal-services?

Thanks!

@jorgeferrer

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
See brianchandotcom/liferay-portal/pull/26090.

Thanks

**Pull request closed without merging**
