### PR TITLE
LPS-103409  As a developer I'd like an API to manage and retrieve SegmentEntry to Role assignments

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-103409](https://issues.liferay.com/browse/LPS-103409).

Hi Eduardo!

This is my attempt at allowing SegmentsEntry models to be associated with Roles. This pull does the following things:

1. Adds an interface `RoleSegmentsEntryManager` to add and remove the associations
2. The `RoleSegmentsEntryManager` uses `SegmentsEntryRel` to add the link, with the `classNameId` being for Role, and the `classPK` being the `roleId`.
3. Adds an interface `RoleSegmentsEntryRetriever` to perform a search for `SegmentsEntry` associated with a particular role. This expects that the `SegmentsEntry` will be indexed with a `roleIds` field.
4. Overloads the `SegmentsEntryLocalService#searchSegmentsEntries` method to accept a `params` map so that we can add the `roleIds` to the search query.
5. `SegmentsEntryRelModelListener` will reindex `SegmentsEntry` after a `Rel` is updated if the classNameId is that of Role.
6. `SegmentsEntryModelDocumentContributor` adds `roleIds` to the document
7. `SegmentsEntryModelPreFilterContributor` adds `roleIds` as a MUST boolean clause to the query if `roleIds` are found in the params

Another note - I copied the logic for creating a `Sort` from `SelectSegmentsEntryDisplayContext` into `RoleSegmentsEntryRetrieverImpl`, so there is duplication there.

The outstanding code design questions are:

1. Should we use a different table than `SegmentsEntryRel` to handle the relationship between Roles and SegmentsEntry?
2. Should we also include the `groupId` in the API of `RoleSegmentsEntryManager`?
3. Should the API be moved to a different module than `roles-admin-api`? If these classes will be useful to other parts of this epic, then we should consider this.

Please let me know what you think!

/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just pushed a fix for the search test failures. Retesting.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/drewbrokke/liferay-portal/pull/904. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/84c6f42238bd~8...84c6f42238bd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
