### PR TITLE
LPS-139008 Add secret as x-api-key header

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:reevaluate:1287401_503

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@epgarcia I merged this in manually.

**Pull request closed without merging**
