### PR TITLE
LPS-99291 Hide content recommendation button if AC is not connected

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76633. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/435f74f7e32b~1...435f74f7e32b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
