### PR TITLE
LPS-139711 - Create style book tokens for all global dialect tokens.

### PR DESCRIPTION
**Pull request by ethib137**
cc @marcoscv-work 

Hey guys, this is a bit of a larger one as it's including all the [global tokens](https://www.figma.com/file/Ekz3GUXzcTSKrsDTYmmBs8/Dialect?node-id=2238%3A151914) from Dialect and seeking to apply them through out Clay. 

There is one commit specifically that you may have questions about: https://github.com/ethib137/liferay-portal/commit/ce47b23a87441ac5a0729923706b662b40a3d479

In this commit I'm overriding the default sass darken function so that I can apply css custom properties to alerts. The darken function will fail on css custom properties since it doesn't know what color it is at compile time. The offending code from alerts is [here](https://github.com/liferay/clay/blob/aa4653f901d22386711b2807c501e9e94a2a1dd5/packages/clay-css/src/scss/components/_alerts.scss#L245).

I have reported this to Clay and we are working on a more wholistic fix:
https://github.com/liferay/clay/issues/4306
https://github.com/liferay/clay/pull/4309/files

In the mean time my fix is to override the default sass darken function and add a check for if it's not a color (in my case that's because its a css custom property). I let css custom properties go through unmodified and I send colors through another function that will do the same thing as darken. Since I've overwritten darken, I'm not able to call it anymore. So instead I'm using a new function that provides a backwards compatible method. Here's how the [sass documentation](https://sass-lang.com/documentation/modules/color#darken) explains it.

> Because darken() is usually not the best way to make a color darker, it’s not included directly in the new module system. However, if you have to preserve the existing behavior, darken($color, $amount) can be written color.adjust($color, $lightness: -$amount).

I hope that all makes sense. Let me know if you have any additional questions.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
LGTM !!!!

**Comment by epgarcia** [comment]
see #1094

**Pull request closed without merging**
