### PR TITLE
LPS-105105 | Unknown entity warning

### PR DESCRIPTION
**Pull request by andresfulla**
@darquesdev

### CODE REVIEW

**Comment by andresfulla** [comment]
ci:test

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82285. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/f01655ba5a40~1...f01655ba5a40) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
