### PR TITLE
LPS-54986

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mosoni @matethurzo

### CODE REVIEW

**Comment by matethurzo** [comment]
Hey,

This is not a bug, this was part of the original design. The folder and the web content should be together by design, since the folder does not do any specific stuff it's just the container. That's why we decided to handle it together.

So this change is not valid from that perspective.

Thanks,

Máté

**Comment by jonathanmccann** [comment]
Hey Máté,

Thanks for the comment. @juliocamarero originally reported the bug so perhaps he can weigh in on why he wanted this implemented.

Thanks!

**Comment by matethurzo** [comment]
He is on vacation now, but we had a conversation earlier that he thought this is a bug, but we cleared that the design was what I wrote to you.

So basically I'm not opposed to add it, but wanted to say this was not part of the design.

**Comment by matethurzo** [comment]
But on the second glance I do not see the performCount() part for folders. If it's not there that would cause more problems.

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Hi @mosoni,

Should we check if "folders" is enabled in the doImportData method, too? Could you please confirm and resend it to @matethurzo?

@matethurzo: The change is fine for us since it brings consistency with DLFolders, but I leave to you the decision to accept the change since as you mentioned it modifies the original design.

Thanks

**Comment by mosoni** [comment]
Hi @matethurzo , @epgarcia , @jonathanmccann 

Thanks for looking into this.
I agree with your point that the it's the part of design behavior, but i made the changes to maintain the consistency like @epgarcia  said i.e. DLfolder can be seen while publishing.

From the "folders" point of view, Yes, it's available in both doExportData and doImportData method but as a part of "web-content" i.e. 
In doExportData method : "folders" logic was implemented along with "web-content" , so i segregated them in this PR and now "folders" and "web-content" logic is handled separately which is like DLFolder implementation.

but i didn't made any changes in doImportData i.e. "folders" logic is still there along with "web-content" logic, so i think it should also be segregated as well.. If yes, then allow me to send you another PR.

Thanks,
Mohit

**Comment by epgarcia** [comment]
Hi @mosoni,

Yes, for consistency with DLFolder the import should be segregated for JournalFolders. It wouldn't make any sense to display the checkbox in the import dialog and ignore it. As I said, please send your new PR to @matethurzo.

Thanks

**Pull request closed without merging**
