### PR TITLE
LPS-100497 Add delete option in the test action menu

### PR DESCRIPTION
**Pull request by dgarciasarai**
From https://github.com/epgarcia/liferay-portal/commit/b5c18c1020514879f293bca3cdc8f9e608c91865 to https://github.com/epgarcia/liferay-portal/commit/9855a2d6bce8cffdef0a2d4a9f3ee844f7fc2c15

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
See brianchandotcom/liferay-portal/pull/77694

**Pull request closed without merging**
