### PR TITLE
LPS-86249

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@epgarcia In modules/apps/segments, I  typed:

grep "String filter"

most of the time, we do "String filterString", but a few times we do "String filter", can you change all "String filter' to "String filterString"? I only noticed it because of this pull. Please resend. thx!

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65201. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/d73d3160f39b~2...d73d3160f39b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65203. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/c0980b3b4b6e~2...c0980b3b4b6e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
