### PR TITLE
LPS-101185 Replace default experience data with the one of the winner declared

### PR DESCRIPTION
**Pull request by darquesdev**
On top of https://github.com/dgarciasarai/liferay-portal/pull/118

### CODE REVIEW

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/90. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/61ed0520abef~1...61ed0520abef) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
