### PR TITLE
LPS-129625 Include non-DXP Commerce modules in Liferay Online

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:stable

**Comment by epgarcia** [comment]
ci:test:liferay-online

**Comment by epgarcia** [comment]
@vicnate5 Could you please take a look at the error in the `ci:test:liferay-online` results? I cannot reproduce it locally, with the same properties. Maybe it is related with https://issues.liferay.com/browse/LPS-129648?

Thanks

```
[echo] Waiting for http://localhost:8080/web/guest to load
  [waitfor] 2021-03-25 01:30:41.120 INFO  [fileinstall-directory-watcher][LicenseManager:?] Portal Development license validation passed
  [waitfor] 2021-03-25 01:30:41.121 INFO  [fileinstall-directory-watcher][LicenseManager:?] License registered for Portal Development
  [waitfor] 2021-03-25 01:30:41.153 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:49] STOPPED Liferay Commerce - Liferay Commerce - API_1.0.0 [177]
  [waitfor] 2021-03-25 01:30:41.157 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:49] STOPPED Liferay Commerce - Liferay Commerce - Impl_1.0.0 [712]
  [waitfor] 2021-03-25 01:30:41.198 INFO  [fileinstall-directory-watcher][BundleBlacklist:189] Stopping blacklisted bundle com.liferay.commerce.application.api_5.0.0 [1509]
  [waitfor] 2021-03-25 01:30:41.209 INFO  [fileinstall-directory-watcher][BundleBlacklist:189] Stopping blacklisted bundle com.liferay.commerce.application.item.selector.api_5.0.0 [1510]
  [waitfor] 2021-03-25 01:30:41.218 ERROR [Framework Event Dispatcher: Equinox Container: fe0367e2-9d4b-4147-aa38-239788e02244][Framework:93] FrameworkEvent ERROR 
  [waitfor] java.lang.NullPointerException
  [waitfor] 	at com.liferay.portal.fragment.bundle.watcher.internal.PortalFragmentBundleWatcher._isFragment(PortalFragmentBundleWatcher.java:171)
  [waitfor] 	at com.liferay.portal.fragment.bundle.watcher.internal.PortalFragmentBundleWatcher.lambda$activate$1(PortalFragmentBundleWatcher.java:73)
  [waitfor] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
  [waitfor] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
  [waitfor] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

**Comment by vicnate5** [comment]
Re-running at https://github.com/vicnate5/liferay-portal/pull/1688. Need to run on my repo to get the licensed bundle compile to see this issue.

**Pull request closed without merging**
