### PR TITLE
LPS-98821 reading errors from fetch

### PR DESCRIPTION
**Pull request by darquesdev**
@andresfulla, @ealonso

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/72. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/8af14ae0efe3~1...8af14ae0efe3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
