### PR TITLE
LPS-96730 Remove portlet preferences for portlets which were removed from the experience

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Hi @pavel-savinov thanks for the PR. I'll review the code tomorrow with @darquesdev and start the tests with @manoelcyreno.

**Comment by andresfulla** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andresfulla** [comment]
I just tested this (as a user) and it works great.

The only minor thing I found is that when creating a new experience with from a Default Experience containing not-configured-yet widget, the new experience does not show that widget.

**Comment by pavel-savinov** [comment]
@epgarcia I've just added Staging support, could you please take a look?

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/manoelcyreno/liferay-portal/pull/17. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/672302b0d40d~3...672302b0d40d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
