### PR TITLE
LPS-98460 add hostname field for segment condition

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76568. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/2db8aae8c69a~2...2db8aae8c69a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76569. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/efff02c97bec~2...efff02c97bec) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76603. [See changes here.](https://github.com/epgarcia/liferay-portal/compare/f1b4b2a7ae1c~3...f1b4b2a7ae1c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
